name: Build Pio Simulator

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  run_linux_tests:
    name: Renode Linux Tests
    uses: ./.github/workflows/piosim_build_linux.yml