name: Build Pio Simulator

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build_for_linux:
    name: PioSim Linux Build 
    uses: ./.github/workflows/piosim_build_linux.yml
  build_for_osx:
    name: PioSim MacOS Build 
    uses: ./.github/workflows/piosim_build_osx.yml