name: Build PioSim For Linux 

on:
  workflow_call:

jobs:
  build_piosim_linux:
    name: "PioSim Linux"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GCC 
        run: |
          sudo apt install gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14 --slave /usr/bin/gcov gcov /usr/bin/gcov-14
          sudo update-alternatives --set gcc /usr/bin/gcc-14

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64 
      
          - name: Build Pio Simulator 
        shell: bash
        run: |
          mkdir build 
          cd build 
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
