name: Build PioSim For Windows 
on:
  workflow_call:

jobs:
  osx_rp2040_tests:
    name: "PioSim Windows"
    runs-on: macos-14 
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Pio Simulator 
        shell: msys2bash.cmd 
        run: |
          mkdir build 
          cd build 
          cmake .. -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .
